export const errorHandler = (err, req, res, next) => {
    console.error(err.stack);
    res.status(500).json({
      error: 'Une erreur interne est survenue. Veuillez rÃ©essayer plus tard.',
      message: err.message,
    });
  };
  